### ISSUE TITLE
Error: cast from pointer to smaller type 'Dword' on MacOS X (64bit)

### ISSUE THREAD

**Issue by dlancer** [h4tr3d/laser-tank#10]
Error on make:

LaserTank.cpp:1270:78: error: cast from pointer to smaller type 'Dword' (aka 'unsigned int') loses information

```
kos_DefineAndDrawWindow(10, 40, 384 + 9, 384 + 25, 0x33, 0x444444, 0, 0, (Dword)header);
```

Latest MacOS X use clang compiler by default, so this is probably related. In my macosx port I just remove this cast:

```
kos_DefineAndDrawWindow(10, 40, 384 + 9, 384 + 25, 0x33, 0x444444, 0, 0, header);
```

**Comment by h4tr3d** [comment]
First form must be used only on KOS
