### ISSUE TITLE
Wrong platform.h inclusion

### ISSUE THREAD

**Issue by dlancer** [h4tr3d/laser-tank#11]
Error on make:
platform/sdl2/macosx/getexepath.cpp:1:10: fatal error: 'platform/platform.h' file not found

In /sdl2/linux this include just not used.

**Comment by h4tr3d** [comment]
What is macosx header contains _NSGetExecutablePath() declaration?

**Comment by dlancer** [comment]
`#include <mach-o/dyld.h>` for _NSGetExecutablePath()

**Comment by h4tr3d** [comment]
I found, thanks :-)
