### ISSUE TITLE
platform/sdl2/platform.cmake

### ISSUE THREAD

**Issue by dlancer** [h4tr3d/laser-tank#13]
Last line:
`set(PLATFORM_LIBS ${SDL2_LIBRARY} ${SDL2_TTF_LIBRARY} m)`

For what for "m" is here?
Btw, with such declaration build failed on cmake 3.0.

**Comment by h4tr3d** [comment]
m - will be expanded to -lm - math library (to use sin/cos and other functions). Also, I have no cmake 3.0.

**Comment by dlancer** [comment]
Да, уже разобрался :)

В общем c "m" и без нее собирается и работает в linux и macosx нормально.

А вот в Haiku где как раз cmake 3.0.0, на "m" ругается ("-lm not
found"), а без нее собирается.
Нужно почитать где это сломано, в 3.0 или в Haiku.

В Haiku без SDL2_ttf уже сделал сборку (т.к. SDL2_ttf в пакетах пока
нет), но пока есть проблемы.

1) Инициализация sdl нормально не проходит (т.к. нет поддержки force
feedback устройств) - это уже решено.

2) Renderer не создается даже software (вылетает по segfault).
Есть вероятность что проблема в VirtualBox (поддержка Haiku в нем
довольно слабая). Нужно проверять на реальном железе. Если и там не
взлетит, то пока видимо не решаемо.


 01/20/2015 07:37 PM, Alexander Drozdov wrote:

**Comment by dlancer** [comment]
I found where is problem. This is not related to cmake.
