### ISSUE TITLE
errno.h not included by default on MacOS X

### ISSUE THREAD

**Issue by dlancer** [h4tr3d/laser-tank#9]
Error on make:
platform/sdl2/kosFile.cpp:15:102: error: use of undeclared identifier 'errno'

kosFile.cpp should be moved  to platform specific or `#include <sys/errno.h>` should be added  to kosFile.cpp

**Comment by h4tr3d** [comment]
Include it via platform.h

**Comment by dlancer** [comment]
platform.h not used in kosFile.cpp

**Comment by dlancer** [comment]
platform.h not used in kosFile.cpp
